name: Deploy Market-Master-Backend to Server

on:
  push:
    branches:
      - main  # 监听 main 分支

jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm install
    - run: npm run build

